version: '3.3'

services:
  web:
    build: .
    command: gunicorn car_makes.wsgi:application --bind 0.0.0.0:8080
    ports:
      - 8080:8080
    env_file:
      - env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.prod

volumes:
  postgres_data: