# Generated by Django 3.1.7 on 2021-03-18 07:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='str: car make', max_length=120)),
                ('model', models.CharField(help_text='str: car model', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(help_text='str: car model rate', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('car', models.ForeignKey(help_text='car', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='car_makes_app.car')),
            ],
        ),
    ]
